// Authentication Handler for DonniDeli
// This file handles all authentication-related operations using Supabase

/**
 * Sign up a new user
 * @param {string} email - User's email address
 * @param {string} password - User's password
 * @returns {Promise<{success: boolean, user?: object, error?: string}>}
 */
async function signUp(email, password) {
    try {
        const { data, error } = await window.supabaseClient.auth.signUp({
            email: email,
            password: password,
            options: {
                emailRedirectTo: `${window.location.origin}/dashboard.html`
            }
        });

        if (error) {
            console.error('Sign up error:', error);
            return {
                success: false,
                error: error.message
            };
        }

        // Note: Barcode is now automatically generated by database trigger
        // No need to manually create it here
        console.log('User created successfully. Barcode will be auto-generated by trigger.');

        return {
            success: true,
            user: data.user
        };
    } catch (error) {
        console.error('Unexpected sign up error:', error);
        return {
            success: false,
            error: 'An unexpected error occurred during sign up'
        };
    }
}

/**
 * Sign in an existing user
 * @param {string} email - User's email address
 * @param {string} password - User's password
 * @returns {Promise<{success: boolean, user?: object, error?: string}>}
 */
async function signIn(email, password) {
    try {
        const { data, error } = await window.supabaseClient.auth.signInWithPassword({
            email: email,
            password: password
        });

        if (error) {
            console.error('Sign in error:', error);
            return {
                success: false,
                error: error.message
            };
        }

        return {
            success: true,
            user: data.user,
            session: data.session
        };
    } catch (error) {
        console.error('Unexpected sign in error:', error);
        return {
            success: false,
            error: 'An unexpected error occurred during sign in'
        };
    }
}

/**
 * Sign out the current user
 * @returns {Promise<{success: boolean, error?: string}>}
 */
async function signOut() {
    try {
        const { error } = await window.supabaseClient.auth.signOut();

        if (error) {
            console.error('Sign out error:', error);
            return {
                success: false,
                error: error.message
            };
        }

        return {
            success: true
        };
    } catch (error) {
        console.error('Unexpected sign out error:', error);
        return {
            success: false,
            error: 'An unexpected error occurred during sign out'
        };
    }
}

/**
 * Send a password reset email
 * @param {string} email - User's email address
 * @returns {Promise<{success: boolean, error?: string}>}
 */
async function resetPassword(email) {
    try {
        const { error } = await window.supabaseClient.auth.resetPasswordForEmail(email, {
            redirectTo: `${window.location.origin}/update-password.html`
        });

        if (error) {
            console.error('Password reset error:', error);
            return {
                success: false,
                error: error.message
            };
        }

        return {
            success: true
        };
    } catch (error) {
        console.error('Unexpected password reset error:', error);
        return {
            success: false,
            error: 'An unexpected error occurred while sending reset email'
        };
    }
}

/**
 * Get the current authenticated user
 * @returns {Promise<object|null>} User object or null if not authenticated
 */
async function getCurrentUser() {
    try {
        const { data: { user }, error } = await window.supabaseClient.auth.getUser();

        if (error) {
            console.error('Get user error:', error);
            return null;
        }

        return user;
    } catch (error) {
        console.error('Unexpected get user error:', error);
        return null;
    }
}

/**
 * Get the current session
 * @returns {Promise<object|null>} Session object or null if not authenticated
 */
async function getSession() {
    try {
        const { data: { session }, error } = await window.supabaseClient.auth.getSession();

        if (error) {
            console.error('Get session error:', error);
            return null;
        }

        return session;
    } catch (error) {
        console.error('Unexpected get session error:', error);
        return null;
    }
}

/**
 * Listen for authentication state changes
 * @param {function} callback - Callback function to handle auth state changes
 * @returns {object} Subscription object
 */
function onAuthStateChange(callback) {
    const { data: { subscription } } = window.supabaseClient.auth.onAuthStateChange((event, session) => {
        callback(event, session);
    });

    return subscription;
}

/**
 * Update user password (when user is already authenticated)
 * @param {string} newPassword - New password
 * @returns {Promise<{success: boolean, error?: string}>}
 */
async function updatePassword(newPassword) {
    try {
        const { error } = await window.supabaseClient.auth.updateUser({
            password: newPassword
        });

        if (error) {
            console.error('Update password error:', error);
            return {
                success: false,
                error: error.message
            };
        }

        return {
            success: true
        };
    } catch (error) {
        console.error('Unexpected update password error:', error);
        return {
            success: false,
            error: 'An unexpected error occurred while updating password'
        };
    }
}

// Export functions for use in other scripts
if (typeof window !== 'undefined') {
    window.authFunctions = {
        signUp,
        signIn,
        signOut,
        resetPassword,
        getCurrentUser,
        getSession,
        onAuthStateChange,
        updatePassword
    };
}
